apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-preprod
  namespace: preprod  # Specify the namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1      
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:                            # Correct indentation for nodeSelectors
        eks.amazonaws.com/nodegroup: preprod    # Specify the node group name    
      containers:
      - name: api
        image: sathish8329/backendpreprod:1255
        ports:
        - containerPort: 8000        
        resources:
          requests:
            memory: "750Mi"    # Lower guaranteed minimum
            cpu: "250m"        # 0.25 CPU core
          limits:
            memory: "1.5Gi"    # Lower maximum
            cpu: "500m"        # 0.5 CPU core
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=1024"          
        livenessProbe:
          httpGet:
            path: /api   # Change this path based on your application's health check endpoint
            port: 8000   # Port where your application is listening
          initialDelaySeconds:  5 # Delay before first probe
          periodSeconds: 10         # How often to perform the probe
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 5  # Adjust as needed
          periodSeconds: 10
          failureThreshold: 3          

---

apiVersion: v1
kind: Service
metadata:
  name: preprod-api-service
  namespace: preprod  # Specify the namespace here
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
