apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-preprod
  namespace: preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1      
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: preprod
      terminationGracePeriodSeconds: 60
      containers:
      - name: api
        image: sathish8329/backendpreprod:1255
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"    # Increased memory request
            cpu: "250m"
          limits:
            memory: "2.5Gi"  # Increased memory limit
            cpu: "500m"
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=2048 --expose-gc --gc-interval=100 --max-semi-space-size=512"
        - name: NODE_ENV
          value: "production"
        - name: V8_MAX_OLD_SPACE_SIZE
          value: "2048"
        - name: V8_HEAP_SIZE_MODIFIER
          value: "0.8"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "node -e 'setInterval(global.gc, 5000)'"]
          preStop:
            exec:
              command: ["/bin/sh","-c","node -e 'global.gc()' && sleep 2"]
        startupProbe:
          httpGet:
            path: /api
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 25
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir:
          sizeLimit: "1Gi"    # Increased tmp volume size

---
apiVersion: v1
kind: Service
metadata:
  name: preprod-api-service
  namespace: preprod
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
