apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-preprod
  namespace: preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1      
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: preprod
      terminationGracePeriodSeconds: 60
      containers:
      - name: api
        image: sathish8329/backendpreprod:1255
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.75Gi"
            cpu: "500m"
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=1400 --expose-gc"
        - name: NODE_ENV
          value: "production"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo 'Node.js container started'"]
          preStop:
            exec:
              command: ["/bin/sh","-c","echo 'Container stopping'"]
        startupProbe:
          httpGet:
            path: /api
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 25
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir:
          sizeLimit: "500Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: preprod-api-service
  namespace: preprod
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
