apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-preprod
  namespace: preprod
spec:
  selector:
    matchLabels:
      app: cron-preprod
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cron-preprod
    spec:
      nodeSelector:                            
        eks.amazonaws.com/nodegroup: preprod-private   
      containers:
      - name: cron-lowcode
        image: sathish8329/cronpreprod:11244
        ports:
        - containerPort: 9000
